// <auto-generated />
namespace StudentFollowApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addColumnSiblingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumnSiblingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202031507429_addColumnSiblingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
